language: csharp
sudo: required
solution: BinaryFormatter.sln

matrix:
  include:
    - dotnet: 1.0.4
      mono: none
      dist: trusty

before_script:
  - chmod a+x ./scripts/build.sh
  - chmod a+x ./scripts/runTests.sh
script:
  - ./scripts/build.sh
  - ./scripts/build.sh
notifications:
  email:
    on_success: never
    on_failure: always