language: csharp
sudo: required
solution: BinaryFormatter.sln

matrix:
  include:
    - dist: trusty
      mono: none
      dotnet: 1.0.4

before_script:
  - chmod -R a+x ./scripts
script:
  - ./scripts/build.sh
  - ./scripts/runTests.sh
notifications:
  email:
    on_success: change
    on_failure: change